"""fixed unique realm name

Revision ID: 1119af9b9af2
Revises: f51b35029ddf
Create Date: 2020-04-24 19:51:37.049178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1119af9b9af2'
down_revision = 'f51b35029ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('badge_ibfk_1', 'badge', type_='foreignkey')
    op.drop_constraint('badge_ibfk_2', 'badge', type_='foreignkey')
    op.create_foreign_key(None, 'badge', 'realm', ['id_realm'], ['id_realm'], source_schema='gamificate', referent_schema='gamificate')
    op.create_foreign_key(None, 'badge', 'reward', ['id_reward'], ['id_reward'], source_schema='gamificate', referent_schema='gamificate')
    op.drop_index('name', table_name='realm')
    op.drop_constraint('realm_ibfk_1', 'realm', type_='foreignkey')
    op.create_foreign_key(None, 'realm', 'admin', ['admin_id'], ['id_admin'], source_schema='gamificate', referent_schema='gamificate')
    op.drop_constraint('reward_ibfk_1', 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'realm', ['id_realm'], ['id_realm'], source_schema='gamificate', referent_schema='gamificate')
    op.drop_constraint('standings_ibfk_2', 'standings', type_='foreignkey')
    op.drop_constraint('standings_ibfk_1', 'standings', type_='foreignkey')
    op.create_foreign_key(None, 'standings', 'user', ['user_id'], ['id_user'], source_schema='gamificate', referent_schema='gamificate')
    op.create_foreign_key(None, 'standings', 'realm', ['realm_id'], ['id_realm'], source_schema='gamificate', referent_schema='gamificate')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'realm', ['id_realm'], ['id_realm'], source_schema='gamificate', referent_schema='gamificate')
    op.drop_constraint('user_badge_ibfk_1', 'user_badge', type_='foreignkey')
    op.drop_constraint('user_badge_ibfk_2', 'user_badge', type_='foreignkey')
    op.create_foreign_key(None, 'user_badge', 'user', ['id_user'], ['id_user'], source_schema='gamificate', referent_schema='gamificate')
    op.create_foreign_key(None, 'user_badge', 'badge', ['id_badge'], ['id_badge'], source_schema='gamificate', referent_schema='gamificate')
    op.drop_constraint('user_reward_ibfk_2', 'user_reward', type_='foreignkey')
    op.drop_constraint('user_reward_ibfk_1', 'user_reward', type_='foreignkey')
    op.create_foreign_key(None, 'user_reward', 'reward', ['id_reward'], ['id_reward'], source_schema='gamificate', referent_schema='gamificate')
    op.create_foreign_key(None, 'user_reward', 'user', ['id_user'], ['id_user'], source_schema='gamificate', referent_schema='gamificate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_reward', schema='gamificate', type_='foreignkey')
    op.drop_constraint(None, 'user_reward', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('user_reward_ibfk_1', 'user_reward', 'reward', ['id_reward'], ['id_reward'])
    op.create_foreign_key('user_reward_ibfk_2', 'user_reward', 'user', ['id_user'], ['id_user'])
    op.drop_constraint(None, 'user_badge', schema='gamificate', type_='foreignkey')
    op.drop_constraint(None, 'user_badge', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('user_badge_ibfk_2', 'user_badge', 'user', ['id_user'], ['id_user'])
    op.create_foreign_key('user_badge_ibfk_1', 'user_badge', 'badge', ['id_badge'], ['id_badge'])
    op.drop_constraint(None, 'user', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'realm', ['id_realm'], ['id_realm'])
    op.drop_constraint(None, 'standings', schema='gamificate', type_='foreignkey')
    op.drop_constraint(None, 'standings', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('standings_ibfk_1', 'standings', 'realm', ['realm_id'], ['id_realm'])
    op.create_foreign_key('standings_ibfk_2', 'standings', 'user', ['user_id'], ['id_user'])
    op.drop_constraint(None, 'reward', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('reward_ibfk_1', 'reward', 'realm', ['id_realm'], ['id_realm'])
    op.drop_constraint(None, 'realm', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('realm_ibfk_1', 'realm', 'admin', ['admin_id'], ['id_admin'])
    op.create_index('name', 'realm', ['name'], unique=True)
    op.drop_constraint(None, 'badge', schema='gamificate', type_='foreignkey')
    op.drop_constraint(None, 'badge', schema='gamificate', type_='foreignkey')
    op.create_foreign_key('badge_ibfk_2', 'badge', 'realm', ['id_realm'], ['id_realm'])
    op.create_foreign_key('badge_ibfk_1', 'badge', 'reward', ['id_reward'], ['id_reward'])
    # ### end Alembic commands ###
