"""column names changed

Revision ID: 124a3b11edb3
Revises: a0529ba828aa
Create Date: 2020-04-11 18:50:19.797924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '124a3b11edb3'
down_revision = 'a0529ba828aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('id_realm', sa.Integer(), nullable=True))
    op.add_column('badge', sa.Column('id_reward', sa.Integer(), nullable=True))
    op.drop_constraint('badge_ibfk_1', 'badge', type_='foreignkey')
    op.drop_constraint('badge_ibfk_2', 'badge', type_='foreignkey')
    op.create_foreign_key(None, 'badge', 'reward', ['id_reward'], ['id_reward'])
    op.create_foreign_key(None, 'badge', 'realm', ['id_realm'], ['id_realm'])
    op.drop_column('badge', 'reward_id')
    op.drop_column('badge', 'realm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('realm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('badge', sa.Column('reward_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'badge', type_='foreignkey')
    op.drop_constraint(None, 'badge', type_='foreignkey')
    op.create_foreign_key('badge_ibfk_2', 'badge', 'reward', ['reward_id'], ['id_reward'])
    op.create_foreign_key('badge_ibfk_1', 'badge', 'realm', ['realm_id'], ['id_realm'])
    op.drop_column('badge', 'id_reward')
    op.drop_column('badge', 'id_realm')
    # ### end Alembic commands ###
