"""column name changed

Revision ID: a0529ba828aa
Revises: baf321519060
Create Date: 2020-04-11 03:33:32.787447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0529ba828aa'
down_revision = 'baf321519060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_realm', sa.Integer(), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'realm', ['id_realm'], ['id_realm'])
    op.drop_column('user', 'realm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('realm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'realm', ['realm_id'], ['id_realm'])
    op.drop_column('user', 'id_realm')
    # ### end Alembic commands ###
