"""total_badges added to user

Revision ID: baf321519060
Revises: c9e437593a77
Create Date: 2020-04-10 21:12:53.125515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf321519060'
down_revision = 'c9e437593a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_badges', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_badges')
    # ### end Alembic commands ###
