"""premium added

Revision ID: dfc3a79d1bb2
Revises: 124a3b11edb3
Create Date: 2020-04-12 22:42:36.427612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc3a79d1bb2'
down_revision = '124a3b11edb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('premium', sa.Boolean(), nullable=True))
    op.drop_index('name', table_name='badge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'badge', ['name'], unique=True)
    op.drop_column('admin', 'premium')
    # ### end Alembic commands ###
