"""added multiple tables

Revision ID: f15cea437f54
Revises: 76382e5c0dac
Create Date: 2020-03-29 20:32:53.625000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15cea437f54'
down_revision = '76382e5c0dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id_reward', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_reward')
    )
    op.create_table('level',
    sa.Column('id_level', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=True),
    sa.Column('b', sa.Integer(), nullable=True),
    sa.Column('c', sa.Integer(), nullable=True),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id_realm'], ),
    sa.PrimaryKeyConstraint('id_level')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id_realm'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('standings',
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('total_badges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id_realm'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('realm_id', 'user_id')
    )
    op.create_table('user_badge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('finished_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id_badge'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('user_reward',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('redeem_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['reward.id_reward'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('user_id', 'reward_id')
    )
    op.add_column('badge', sa.Column('reward_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'badge', 'reward', ['reward_id'], ['id_reward'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'badge', type_='foreignkey')
    op.drop_column('badge', 'reward_id')
    op.drop_table('user_reward')
    op.drop_table('user_badge')
    op.drop_table('standings')
    op.drop_table('user')
    op.drop_table('level')
    op.drop_table('reward')
    # ### end Alembic commands ###
