"""username added

Revision ID: 106126e052b3
Revises: f15cea437f54
Create Date: 2020-04-10 16:37:35.285819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106126e052b3'
down_revision = 'f15cea437f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
