"""moved level up parameters to realm

Revision ID: 1a73ed6a9a06
Revises: 34795b6471ba
Create Date: 2020-04-18 20:54:27.401761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a73ed6a9a06'
down_revision = '34795b6471ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level')
    op.add_column('realm', sa.Column('a', sa.Float(), nullable=True))
    op.add_column('realm', sa.Column('b', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realm', 'b')
    op.drop_column('realm', 'a')
    op.create_table('level',
    sa.Column('id_level', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('a', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('realm_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id_realm'], name='level_ibfk_1'),
    sa.PrimaryKeyConstraint('id_level'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
