"""added level up parameters

Revision ID: 34795b6471ba
Revises: 6f9634881328
Create Date: 2020-04-18 19:45:42.081678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34795b6471ba'
down_revision = '6f9634881328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('c', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
