"""added api key

Revision ID: 6f9634881328
Revises: 71e2f77bf3ed
Create Date: 2020-04-14 20:16:47.348777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9634881328'
down_revision = '71e2f77bf3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realm', sa.Column('api_key', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'realm', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realm', type_='unique')
    op.drop_column('realm', 'api_key')
    # ### end Alembic commands ###
