"""rewards added on realm

Revision ID: 71e2f77bf3ed
Revises: dfc3a79d1bb2
Create Date: 2020-04-13 15:12:32.258851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e2f77bf3ed'
down_revision = 'dfc3a79d1bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('id_realm', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reward', 'realm', ['id_realm'], ['id_realm'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.drop_column('reward', 'id_realm')
    # ### end Alembic commands ###
