"""add badges

Revision ID: 76382e5c0dac
Revises: f3bc7c5f757e
Create Date: 2020-03-28 14:51:15.763117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76382e5c0dac'
down_revision = 'f3bc7c5f757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id_badge', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('required', sa.Integer(), nullable=True),
    sa.Column('realm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id_realm'], ),
    sa.PrimaryKeyConstraint('id_badge'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    # ### end Alembic commands ###
